import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      username: "aziz",
      email: "zzbrgch@gmail.com",
      password: bcrypt.hashSync("CAt3rnjutnBEzB8"),
      isAdmin: true,
    },
    {
      username: "bergach",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("Py2GQh7Q6dwr8if"),
      isAdmin: false,
    },
    {
      username: "test",
      email: "test@email.com",
      password: bcrypt.hashSync("Py2GQh7Q6dwr8if"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      isFeatured: true,
      featuredImage: "/images/banner2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
  reviews: [
    {
      createdAt: "1640749909000",
      createdBy: "aziz",
      slug: "free-shirt",
      rating: 5,
      comment: "its a good product !!",
    },
    {
      createdAt: "1646749009035",
      createdBy: "bergach",
      slug: "free-shirt",
      rating: 3,
      comment: "I like the color of this shirt, it made me a wonderfull !!",
    },
  ],
};
export default data;
